 spring:
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring?serverTimezone=GMT
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

